"""Configuration Package"""

from .agent_config import (
    BEDROCK_MODEL_ID,
    BEDROCK_REGION,
    AGENT_CONFIG,
    MCP_SERVERS,
    MCP_TOOL_REGISTRY_PATH,
    ROLE_SUPERVISOR,
    ROLE_AGRI_EXPERT,
    ROLE_POLICY_NAVIGATOR,
    ROLE_RESOURCE_OPTIMIZER,
    AWS_REGION,
    DYNAMODB_TABLE_NAME,
    S3_BUCKET_NAME,
    BEDROCK_KB_ID,
    SUPPORTED_LANGUAGES,
    DEFAULT_LANGUAGE
)

__all__ = [
    'BEDROCK_MODEL_ID',
    'BEDROCK_REGION',
    'AGENT_CONFIG',
    'MCP_SERVERS',
    'MCP_TOOL_REGISTRY_PATH',
    'ROLE_SUPERVISOR',
    'ROLE_AGRI_EXPERT',
    'ROLE_POLICY_NAVIGATOR',
    'ROLE_RESOURCE_OPTIMIZER',
    'AWS_REGION',
    'DYNAMODB_TABLE_NAME',
    'S3_BUCKET_NAME',
    'BEDROCK_KB_ID',
    'SUPPORTED_LANGUAGES',
    'DEFAULT_LANGUAGE'
]
